# Generated by Django 5.0.3 on 2024-05-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0005_alter_userprofile_overall_success_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
