# Generated by Django 5.0.3 on 2024-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0006_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
