# Generated by Django 5.0.3 on 2024-05-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0010_userprofile_education_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English')], max_length=50),
        ),
    ]
