# Generated by Django 5.0.3 on 2024-05-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0012_userprofile_condition_userprofile_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
