# Generated by Django 5.0.3 on 2024-05-11 01:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0013_alter_userprofile_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QS_MEMORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('qs', models.TextField()),
                ('ans', models.CharField(max_length=25)),
                ('w_ans', models.CharField(max_length=25)),
                ('w2_ans', models.CharField(max_length=25)),
            ],
        ),
    ]
