# Generated by Django 5.0.3 on 2024-05-14 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0015_userprofile_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='memoqui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_score', models.IntegerField(default=0)),
                ('avareg_last_5', models.IntegerField(default=0)),
                ('previous_s_rate', models.IntegerField(default=0)),
                ('present_s_rate', models.IntegerField(default=0)),
                ('last_1', models.IntegerField(default=0)),
                ('last_2', models.IntegerField(default=0)),
                ('last_3', models.IntegerField(default=0)),
                ('last_4', models.IntegerField(default=0)),
                ('last_5', models.IntegerField(default=0)),
                ('last_6', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
