# Generated by Django 5.0.3 on 2024-05-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0016_memoqui'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoqui',
            old_name='user',
            new_name='userdetails',
        ),
    ]
