# Generated by Django 5.0.3 on 2024-05-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0017_rename_user_memoqui_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoqui',
            old_name='userdetails',
            new_name='user',
        ),
    ]
