# Generated by Django 5.0.3 on 2024-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brainer', '0018_rename_userdetails_memoqui_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='score',
            new_name='memoeui_de_score',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_avareg_last_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_high_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_last_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_present_s_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memoeui_de_previous_s_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='memoqui',
        ),
    ]
